version: '3'

services:
  nginx:
    build:
      context: nginx
      args:
        BUILD_ENVIRONMENT: ${BUILD_ENVIRONMENT}
    networks:
      default-network :
         ipv4_address: ${NGINX_IPV4_ADDRESS}
    ports:
      - ${APP_PORT}:80
      - ${APP_SSL_PORT}:443
    depends_on:
      - phpfpm
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
      - ${NGINX_SSL_SOURCE_PATH}:${NGINX_SSL_VOLUME_PATH}
  phpfpm:
    build:
      context: php
      args:
        SOURCE_PATH: ${SOURCE_PATH}
        VOLUME_PATH: ${VOLUME_PATH}
        PHP_VERSION: ${PHP_VERSION}
    networks:
      default-network :
         ipv4_address: ${PHPFPM_IPV4_ADDRESS}
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    tty: true
    ports:
      - "6379:6379"
    networks:
      default-network :
         ipv4_address: ${REDIS_IPV4_ADDRESS}
  #MySQL Service
  db:
    image: mysql:8.0
    container_name: db
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci --secure-file-priv=NULL
    restart: always
    tty: true
    ports:
      - "33067:3306"
    environment:
        MYSQL_DATABASE: test
        MYSQL_USER: mysql
        MYSQL_PASSWORD: 123456
        MYSQL_ROOT_PASSWORD: 123456
        SERVICE_TAGS: dev
        SERVICE_NAME: mysql
    volumes:
      #- dbdata:/var/lib/mysql-files/
      - ./database/init/:/docker-entrypoint-initdb.d/
      - ./mysql/:/etc/mysql/
    networks:
      default-network :
         ipv4_address: ${MYSQL_IPV4_ADDRESS}
  postgresql:
    image: postgres
    networks:
      default-network :
         ipv4_address: ${POSTGRE_IPV4_ADDRESS}
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=
    volumes:
      - postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgresql:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
    ulimits:
      nofile:
       soft: 65536
       hard: 65536
    networks:
      default-network :
         ipv4_address: ${SONAR_SERVER_URL}

networks:
  default-network:
    driver: bridge
    ipam:
     config:
       - subnet: ${DOCKER_SUBNET}
volumes:
  sonarqube_conf:
  sonarqube_data:
  postgresql:
  postgresql_data: