version: '3'
name: docker_ubuntu

services:
  ubuntu:
    container_name: ubuntu
    build: ./ubuntu
    working_dir: ${VOLUME_PATH}
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
  apache:
    container_name: apache_server
    build: 
      context: ./apache
    ports:
      - ${APP_PORT}:80
      - ${APP_SSL_PORT}:443
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
      - ./apache/conf/apache2.conf:/etc/apache2/apache2.conf
    depends_on:
      - mysql
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
