version: '3'
name: docker_ubuntu

services:
  ubuntu:
    container_name: ubuntu
    build: ./ubuntu
    working_dir: ${VOLUME_PATH}
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
  apache:
    container_name: apache_server
    restart: always
    extra_hosts:
      - "local.biz-admin.tk:127.0.0.1"
    build:
      context: ./apache
    ports:
      - ${APP_PORT}:80
      - ${APP_SSL_PORT}:443
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
      - ./apache/conf/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/php/php.ini:/usr/local/etc/php/php.ini
      - ./apache/conf/conf-available/letsencrypt.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - mysql
    environment:
      WEBMASTER_MAIL: "admin@gmail.com"
      DOMAINS: "biz-admin.tk,www.biz-admin.tk"
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: db_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456a@