version: '3'
name: docker_ubuntu

services:
  ubuntu:
    container_name: ubuntu
    build: ./ubuntu
    working_dir: ${VOLUME_PATH}
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
  apache:
    container_name: apache_server
    build:
      context: ./apache
    ports:
      - ${APP_PORT}:80
      - ${APP_SSL_PORT}:443
    volumes:
      - ${SOURCE_PATH}:${VOLUME_PATH}
      - ./apache/conf/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/php/php.ini:/usr/local/etc/php/php.ini
      - ./conf/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./apache/conf/conf-available/letsencrypt.conf:/etc/apache2/conf-available/letsencrypt.conf
      - ./apache/conf/conf-available/ssl-params.conf:etc/apache2/conf-available/ssl-params.conf
      - ./apache/conf/sites-available/local.biz_match.com.conf:/etc/apache2/sites-available/local.biz_match.com.conf
    depends_on:
      - mysql
      - letsencryptstore
    environment:
      WEBMASTER_MAIL: "admin@gmail.com"
      DOMAINS: "local.biz-match.com,www.local.biz-match.com"
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456a@
  # letsencryptstore:
  #   image: busybox
  #   volumes:
  #     - "/etc/letsencrypt"
  #     - "/var/lib/letsencrypt"